<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Version>0.9.10</Version>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <Reference Include="office" Private="true">
      <HintPath>$(NuGetPackageRoot)microsoft.office.core\12.0.0\Office.dll</HintPath>
    </Reference>
    <PackageReference Include="Microsoft.Office.Core" Version="12.0.0" />
    <ProjectReference Include="..\PresenterConsole.Contracts\PresenterConsole.Contracts.csproj" />
    <ProjectReference Include="..\PresenterConsole.Sync\PresenterConsole.Sync.csproj" />
    <PackageReference Include="QRCoder" Version="1.6.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.8" />
    <PackageReference Include="Microsoft.Office.Interop.PowerPoint" Version="15.0.4420.1018" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="wwwroot\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
